name: Software Composition Analysis
run-name: SCA ⚡️

on:
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC
  pull_request:
    branches: ["**"]

permissions: {}

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write

    steps:
      - name: Run SCA
        uses: ministryofjustice/devsecops-actions/sca@7dc13c20e2bf541b8a77fa1320a04983b18846f6 # v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
